### PR TITLE
Update mandel.hs

### PR DESCRIPTION
**Pull request by mpickering**

### CODE REVIEW

**Comment by mpickering** [comment]
I think the library is quite broken anyway. Compiling the example and indeed trying any program 
yields exceptions with anything I have tried. 

```
~/Documents/haskell:./dense 
dense: Prelude.undefined
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/Err.hs:79:14 in base:GHC.Err
  undefined, called at ./Data/Vector/Primitive/Mutable.hs:100:22 in vector-0.11.0.0-HhutbadagxHIONIkSRJEug:Data.Vector.Primitive.Mutable
```

**Comment by cchalmers** [comment]
Thanks. The example was actually pretty broken so I rewrote it (11f1ffc457b40b182ade579a3453a981a30b7047).

However I didn't get a `Prelude.undefined` error message. I'm not sure what's causing that. What ghc version are you using? Could you try installing `dense` with the latest version of `vector`?

**Comment by mpickering** [comment]
With the latest version of vector it works.

**Comment by cchalmers** [comment]
Thanks. I'll update the version bounds.

**Pull request closed without merging**
